# Generated by Django 3.2.18 on 2023-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.TextField(default='password'),
            preserve_default=False,
        ),
    ]
