# Generated by Django 3.2.18 on 2023-04-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.TextField(unique=True),
        ),
    ]
