# Generated by Django 3.2.18 on 2023-04-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20230412_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
