# Generated by Django 3.2.18 on 2023-04-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
