# Generated by Django 3.2.18 on 2023-04-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20230412_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
    ]
