# Generated by Django 3.2.18 on 2023-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
