# Generated by Django 3.2.18 on 2023-04-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20230412_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.TextField(default='paciente'),
        ),
    ]
