# Generated by Django 3.2.18 on 2023-04-15 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='pacienteD',
            field=models.ForeignKey( on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='doctor',
            field=models.TextField(),
        ),
    ]
